"""
LLM/RAG Fraud Investigation Co-pilot Prototype
==============================================
"""

import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.neighbors import NearestNeighbors
from sklearn.calibration import CalibratedClassifierCV
from lightgbm import LGBMClassifier

REPORT = "reports/llm_copilot_prototype_report.md"
TRAIN_PATH = "data/split/train.csv"

def wmd(txt, mode='a'):
    with open(REPORT, mode, encoding='utf-8') as f:
        f.write(txt + "\n")

def make_preprocessor(num_cols, cat_cols):
    nt = Pipeline([('imp', SimpleImputer(strategy='median')), ('scaler', StandardScaler())])
    ct = Pipeline([('imp', SimpleImputer(strategy='most_frequent')),
                   ('ohe', OneHotEncoder(handle_unknown='ignore', sparse_output=False))])
    return ColumnTransformer([('n', nt, num_cols), ('c', ct, cat_cols)])

def generate_evidence(row, cols):
    ev = []
    if row['tslt_is_missing'] == 1:
        ev.append("- TSLT is missing; historically this group has near-zero fraud. This strongly lowers risk.")
    if row['is_new_location_for_sender'] == 1:
        ev.append("- Sender is using a new location for the first time.")
    if row['is_new_device_used_for_sender'] == 1:
        ev.append("- Sender is using a new device type for the first time.")
    if row['is_new_payment_channel_for_sender'] == 1:
        ev.append("- Sender is using a new payment channel.")
    if row['is_new_transaction_type_for_sender'] == 1:
        ev.append("- Sender is using a new transaction type.")
    if row['is_night'] == 1:
        ev.append(f"- Transaction occurred at night ({row['hour']}h).")
    
    amount = row['amount']
    ev.append(f"- Amount: ${amount:.2f} via {row['payment_channel']} ({row['transaction_type']})")
    
    if len(ev) <= 2 and row['tslt_is_missing'] == 0:
        ev.append("- No obvious behavioral anomalies detected in standard features.")
        
    return ev

def generate_mock_llm_report(tx_id, score, rank, band, action, risk_factors, similar_cases):
    r = []
    r.append(f"### Fraud Investigation Brief: `{tx_id}`")
    r.append(f"**Transaction ID**: {tx_id}")
    r.append(f"**Model Risk Score**: {score:.4f} (Ranked Top {rank:.2f}%)")
    r.append(f"**Risk Band**: {band}")
    r.append(f"**Recommended Action**: **{action}**")
    r.append("\n**Key Risk Factors**:")
    for f in risk_factors:
        r.append(f)
        
    r.append("\n**Similar Historical Cases (Retrieved via RAG)**:")
    for idx, sc in enumerate(similar_cases):
        r.append(f"{idx+1}. Dist: {sc['dist']:.2f} | Label: **{sc['label']}** | Amount: ${sc['amt']:.2f} | Note: {sc['note']}")
        
    r.append("\n**Why This Was Flagged**:")
    reasons = []
    if band == "High":
        reasons.append("This transaction shares risk indicators with known historical cases.")
    elif band == "Review":
        reasons.append("The model detected anomalies. The retrieved history shows mixed outcomes for similar patterns.")
    elif band == "Medium":
        reasons.append("This transaction has some novelty flags but lacks the definitive markers of historical fraud.")
    else:
        reasons.append("This transaction fits the user's historical profile perfectly or falls into a safe structural bucket.")
        
    if len(risk_factors) <= 2:
        reasons.append("Evidence is weak.")
        
    r.append(" ".join(reasons))
        
    r.append("\n**Caveats**:")
    r.append("- *Weak Model Signal*: The underlying Cascade model is a weak ranking signal. High score does not guarantee fraud.")
    r.append("- *RAG Limitations*: Similar transactions retrieved are based on structured features, not explicit causal links.")
    r.append("- *Prototype System*: This brief is generated by a template-based prototype (LLM-ready); no real LLM call was used.")
    
    r.append("\n**Suggested Analyst Next Step**:")
    if action == "Escalate to senior analyst":
        r.append("Contact the sender via registered phone number to verify intent.")
    elif action == "Manual review":
        r.append("Check account creation date and verify transaction details.")
    elif action == "Monitor":
        r.append("Allow transaction but flag the device for 24-hour monitoring.")
    else:
        r.append("No immediate action required.")
        
    r.append("---\n")
    return "\n".join(r)

def main():
    wmd("# LLM/RAG FRAUD INVESTIGATION CO-PILOT PROTOTYPE REPORT\n", 'w')
    wmd("## A. Objective\nBuild a prototype demonstrating a hybrid ML+LLM workflow where a Cascade model filters transactions and a RAG/LLM system generates evidence-based Analyst Briefs.\n")
    wmd("## B. System Architecture\n1. **Component A (Scorer)**: LightGBM Cascade B.\n2. **Component B (Evidence)**: Fact extractor.\n3. **Component C & D (RAG/Retriever)**: NearestNeighbors on historical corpus.\n4. **Component E (Report Generator)**: Strict Prompt/Template logic.\n")
    wmd("## C. Data Flow\n`Raw Transaction -> Feature Engineering -> Cascade Score -> RAG Retrieval -> LLM Prompt -> Analyst Report`\n")
    
    print("Loading datasets...")
    df = pd.read_csv(TRAIN_PATH, parse_dates=['timestamp'])
    df = df.sort_values('timestamp').reset_index(drop=True)
    
    print("Building features...")
    df['log_amount'] = np.log1p(df['amount'])
    df['hour'] = df['timestamp'].dt.hour
    df['day_of_week'] = df['timestamp'].dt.dayofweek
    df['month'] = df['timestamp'].dt.month
    df['is_weekend'] = df['day_of_week'].isin([5,6]).astype(int)
    df['is_night'] = ((df['hour']>=0)&(df['hour']<=5)).astype(int)
    df['tslt_abs'] = df['time_since_last_transaction'].abs()
    df['tslt_is_missing'] = df['time_since_last_transaction'].isnull().astype(int)
    df['tslt_is_negative'] = (df['time_since_last_transaction']<0).astype(int)
    
    pairs = [
        ('sender_account', 'location', 'sender_location_pair_count_past', 'is_new_location_for_sender'),
        ('sender_account', 'payment_channel', 'sender_channel_pair_count_past', 'is_new_payment_channel_for_sender'),
        ('sender_account', 'device_used', 'sender_device_type_pair_count_past', 'is_new_device_used_for_sender'),
        ('sender_account', 'transaction_type', 'sender_txn_type_pair_count_past', 'is_new_transaction_type_for_sender'),
    ]
    for s, v, cnt_f, nov_f in pairs:
        df2 = df[[s, v, 'timestamp']].copy()
        df2['oi'] = df2.index
        df2 = df2.sort_values([s, v, 'timestamp'])
        df2['pc'] = df2.groupby([s, v]).cumcount()
        df2 = df2.sort_values('oi')
        df[nov_f] = (df2['pc'].values == 0).astype(int)

    NUM_FS1 = ['amount','log_amount','spending_deviation_score','velocity_score',
               'geo_anomaly_score','hour','day_of_week','month','is_weekend','is_night',
               'tslt_abs','tslt_is_missing','tslt_is_negative',
               'is_new_location_for_sender','is_new_payment_channel_for_sender',
               'is_new_transaction_type_for_sender','is_new_device_used_for_sender']
    NUM_HARD = [c for c in NUM_FS1 if c != 'tslt_is_missing']
    CAT_COLS = ['transaction_type','merchant_category','payment_channel','device_used','location']
    
    train_inner = df.iloc[:3200000]
    validation = df.iloc[3200000:]
    y_tr = train_inner['is_fraud'].astype(int)
    y_va = validation['is_fraud'].astype(int)
    
    lgbm_config = dict(n_estimators=100, learning_rate=0.05, random_state=42, n_jobs=-1, verbose=-1) # Faster

    # Train M1 Calibrated (Cascade B) on subset to speed up Prototype
    print("Training Prototype Scorer...")
    h_tr = train_inner['tslt_is_missing'] == 0
    X_tr_h = train_inner[h_tr].iloc[-200000:] # Sample for speed
    y_tr_h = y_tr[h_tr].iloc[-200000:]
    
    pre1 = make_preprocessor(NUM_HARD, CAT_COLS)
    X_tr_h_trans = pre1.fit_transform(X_tr_h[NUM_HARD+CAT_COLS])
    
    cal_mdl = CalibratedClassifierCV(estimator=LGBMClassifier(**lgbm_config), method='sigmoid', cv=3)
    cal_mdl.fit(X_tr_h_trans, y_tr_h)
    
    X_va = validation[NUM_HARD+CAT_COLS]
    X_va_trans = pre1.transform(X_va)
    m1_cal_val_probs = cal_mdl.predict_proba(X_va_trans)[:,1]
    
    is_missing_va = validation['tslt_is_missing'].values == 1
    score_B = np.where(is_missing_va, 1e-6, m1_cal_val_probs)
    
    # RAG Corpus Builder
    print("Building RAG Corpus & Retriever...")
    corpus_idx = train_inner.iloc[-100000:].groupby('is_fraud').apply(lambda x: x.sample(2000, random_state=42)).index.get_level_values(1)
    corpus_df = train_inner.loc[corpus_idx]
    corpus_trans = pre1.transform(corpus_df[NUM_HARD+CAT_COLS])
    
    retriever = NearestNeighbors(n_neighbors=3, algorithm='auto')
    retriever.fit(corpus_trans)
    
    print("Sampling Transactions for Prototype...")
    # Get percentiles
    p_001 = np.percentile(score_B, 99.9)
    p_01 = np.percentile(score_B, 99.0)
    p_05 = np.percentile(score_B, 95.0)
    
    samples = []
    # 2 High Risk (Top 0.1%)
    idx_high = np.where(score_B >= p_001)[0][:2]
    # 2 Review (Top 1%)
    idx_rev = np.where((score_B >= p_01) & (score_B < p_001))[0][:2]
    # 2 Medium (Top 5%)
    idx_med = np.where((score_B >= p_05) & (score_B < p_01))[0][:2]
    # 2 Low Risk
    idx_low = np.where(score_B < 1e-5)[0][:2]
    
    sample_idxs = np.concatenate([idx_high, idx_rev, idx_med, idx_low])
    
    wmd("## D. Components Implemented\n- Risk Scorer: Cascade B (Simulated)\n- Evidence Builder: Fact extraction\n- RAG Corpus: 4,000 historical cases\n- Retriever: Scikit-learn NearestNeighbors\n- Report Generator: Strict Prompting Logic\n")
    
    wmd("## E. Prompt Template for LLM\n")
    wmd("""```text
System: You are a Fraud Analyst Co-pilot. Your job is to strictly format the provided evidence and RAG retrieved cases into an Analyst Brief. Do NOT hallucinate. Do NOT expose internal chain of thought. Maintain a professional, objective tone. Acknowledge that the model provides weak ranking signals.

User:
Generate a Fraud Investigation Brief for the following data:
- Transaction ID: {tx_id}
- Score: {score}
- Band: {band}
- Action: {action}
- Evidence: {risk_factors}
- RAG Cases: {similar_cases}

Format exactly as specified in the guidelines.
```\n""")
    
    wmd("## F. Sample Outputs (Generated by Mock Co-pilot)\n")
    
    for i in sample_idxs:
        row = validation.iloc[i]
        score = score_B[i]
        tx_id = row.get('transaction_id', f"TXN_{i}")
        
        # Rank logic
        if score >= p_001:
            band, action, rank = "High", "Escalate to senior analyst", 0.1
        elif score >= p_01:
            band, action, rank = "Review", "Manual review", 1.0
        elif score >= p_05:
            band, action, rank = "Medium", "Monitor", 5.0
        else:
            band, action, rank = "Low", "Approve under current policy", 99.0
            
        evidence = generate_evidence(row, NUM_FS1)
        
        # Retrieval
        q_trans = pre1.transform(validation.iloc[[i]][NUM_HARD+CAT_COLS])
        dists, inds = retriever.kneighbors(q_trans)
        
        sim_cases = []
        for d, idx in zip(dists[0], inds[0]):
            c_row = corpus_df.iloc[idx]
            sim_cases.append({
                'dist': d,
                'label': "Fraud" if c_row['is_fraud'] else "Legitimate",
                'amt': c_row['amount'],
                'note': f"Channel: {c_row['payment_channel']}, Device: {c_row['device_used']}"
            })
            
        report = generate_mock_llm_report(tx_id, score, rank, band, action, evidence, sim_cases)
        wmd(report)

    wmd("""
## G. Safety and Guardrails
- **No hidden chain-of-thought exposure**: The report strictly outputs formatted conclusions.
- **No automatic blocking**: The highest severity action recommended is 'Escalate to senior analyst'.
- **No hallucinated evidence**: All facts are extracted purely from the transaction row features.
- **Human-in-the-loop**: The report explicitly suggests steps for human verification.
- **Weak model caveat**: Explicitly stated in the Caveats section of every brief.

## H. Limitations
- Dataset lacks raw textual case notes (e.g., analyst chat logs) which would make RAG much more powerful.
- Retriever currently uses structural nearest neighbors rather than true semantic/text embeddings.
- Model signal ceiling remains at ~5% Precision; the report contextualizes this but cannot invent signal.
- The TSLT missing artifact heavily skews the distribution of "Safe" transactions.

## I. Production Roadmap

### Phase 1 — Offline Demo (Current)
- Batch scoring with Cascade B and generated structural reports for stakeholder demonstration.

### Phase 2 — Analyst Dashboard
- Build a Web UI (Review Queue) where analysts can click on a flagged transaction and instantly see the generated investigation brief.

### Phase 3 — Human Feedback Loop
- Add "Approve" / "Reject" buttons. Analysts' feedback will act as explicit PU Learning labels to retrain the hard-subset model.

### Phase 4 — Real-time Deployment
- Deploy the feature engineering logic into a Flink stream. Use an optimized ONNX version of LightGBM for <20ms latency. Send only top 1% to the LLM backend.

### Phase 5 — Enterprise-grade System
- Implement robust drift detection, audit logging of LLM responses, and full API integration with core banking systems for temporary fund holds.

## J. Productization Summary — Hybrid Fraud Review Co-pilot

The prototype demonstrates a hybrid fraud-review workflow that combines a weak but validated ML ranking model with a template-based, LLM-ready investigation brief generator.

The Cascade/LightGBM layer acts as the first-stage scorer. The retrieval layer surfaces structurally similar historical transactions. The report generator converts the model score, extracted feature evidence, and retrieved neighbors into a concise analyst-facing brief.

This extension improves explainability and review workflow, but it does not improve the underlying fraud classification performance. The system should therefore be positioned as a human-in-the-loop analyst assistant, not as an autonomous fraud detector.

The current implementation is a mock/template-based prototype. It does not call a live LLM and does not use true semantic case-note retrieval. A production-grade version would require real analyst case notes, stronger retrieval data, audit logging, hallucination controls, feedback capture, drift monitoring, and a formally approved action policy.
""")
    
    print("Prototype Completed!")

if __name__ == "__main__":
    main()
